### ISSUE TITLE
question about variance

### ISSUE THREAD

**Issue by Fangwq** [Magica-Chen/gptp_multi_output#4]
A little confuse about the code in the tp_solve_gpml.m file. The code is as following:

```
      % Solve the variance
      v = L\K21';
      Varft = (diag(K22) - sum(v.^2,1)')*(nu+beta1-2)/(nu+n-2);
      
      % Return
      varargout = {Eft,Varft};
      
      % Solve the full covariance matrix
      if nargout>2
          Covft = (K22 - v'*v)*(nu+beta1-2)/(nu+n-2);
          varargout = {Eft,Varft,Covft};
      end
      
      % Also return the 95% interval
      if nargout>3
          lb = Eft + tinv(0.025,nu+n)*sqrt(Varft);
          ub = Eft + tinv(0.975,nu+n)*sqrt(Varft);
          varargout = {Eft,Varft,Covft,lb,ub};
      end
```
Why do you solve the variance as above ? It is not ```sqrt(diag(Covft)))``` ?

**Comment by Magica-Chen** [comment]
1. If nargout <=2, we only need variance rather than covariance (covariance is more complicated than variance). So we will compute variance first, and if necessary we compute covariance.
2. Of course, you can also compute covariance fist and then achieve variance, but I don't think it is an efficient approach because diag(K22) - sum(V.^2, 1)' should be faster than (K22 - v'v).

**Comment by Fangwq** [comment]
OK, thanks for your clarification.

**Comment by Magica-Chen** [comment]
Clarified
